services:
  mysql:
    image: mysql:8.0.45-debian
    container_name: mysql-3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kohobank
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10

  card-service:
    image: kohodocker/card-service:v1
    build: .
    container_name: card
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9000:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kohonet
networks:
  kohonet:
    driver: "bridge"