spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway"
    description: "KOHO Bank Gateway Application"
    version: "v1.0"

logging:
  level:
    com:
      koho:
        apigateway: DEBUG