#spring.application.name=account-service

#Timeout
#spring.config.activate.on-profile=qa


# Command line arguments - Program arguments(Intellij)
# --spring.profiles.active=prod --build.version=1.1

# JVM system variable - Add VM options (Intellij)
# -Dspring.profiles.active=prod -Dbuild.version=1.2

# Environment variables - Environment variables (intellij)
# SPRING_PROFILES_ACTIVE=prod;BUILD_VERSION=1.3;